import { mount } from 'svelte'
import App from './App.svelte'
import { registerSW } from 'virtual:pwa-register'

// Register the service worker (generated by vite-plugin-pwa / Workbox).
// 'autoUpdate' strategy: new content is applied automatically on the next load.
// In dev (no SW emitted) and on unsupported browsers this is a no-op.
registerSW({ immediate: true })

const app = mount(App, {
  target: document.getElementById('app')!,
})

export default app
