import { mount } from 'svelte'
import './app.css'
import App from './App.svelte'
import { Settings } from './state/settings.svelte'
import { registerSW } from 'virtual:pwa-register'
import { pwaUpdate } from './state/pwaUpdate.svelte'

// Register the service worker (generated by vite-plugin-pwa / Workbox).
// 'prompt' strategy: a new build installs but waits; we surface it via pwaUpdate
// (UpdateToast) and apply it only on the user's command — `updateSW(true)` skips
// waiting and reloads. On unsupported browsers this is a no-op.
const updateSW = registerSW({
  immediate: true,
  onNeedRefresh() {
    pwaUpdate.bind(() => updateSW(true))
  },
})

// Construct settings *before* mount: its constructor applies the saved theme + CSS vars to the
// document root, so the first paint already reflects the user's preferences (no theme flash).
const settings = new Settings()

const app = mount(App, {
  target: document.getElementById('app')!,
  props: { settings },
})

export default app
