import { mount } from 'svelte'
import './app.css'
import App from './App.svelte'
import { Settings } from './state/settings.svelte'
import { registerSW } from 'virtual:pwa-register'

// Register the service worker (generated by vite-plugin-pwa / Workbox).
// 'autoUpdate' strategy: new content is applied automatically on the next load.
// In dev (no SW emitted) and on unsupported browsers this is a no-op.
registerSW({ immediate: true })

// Construct settings *before* mount: its constructor applies the saved theme + CSS vars to the
// document root, so the first paint already reflects the user's preferences (no theme flash).
const settings = new Settings()

const app = mount(App, {
  target: document.getElementById('app')!,
  props: { settings },
})

export default app
