package dev.noveditor.core.model

import kotlinx.serialization.Serializable
import kotlin.jvm.JvmInline

/**
 * Stable identifier of a [Manuscript].
 *
 * Wraps a [String] so ids are not confused with arbitrary strings at the type level.
 * The concrete value is generated by an adapter (e.g. `crypto.randomUUID()` on web,
 * `UUID` on Android) and injected into [core][dev.noveditor.core]; `core` never mints ids itself.
 */
@Serializable
@JvmInline
value class ManuscriptId(val value: String)

/**
 * A single writing target: title, body and creation/update timestamps.
 *
 * Timestamps are epoch milliseconds supplied by an adapter (`core` holds no clock).
 * Serializable via kotlinx.serialization so adapters share one canonical persistence shape.
 */
@Serializable
data class Manuscript(
    val id: ManuscriptId,
    val title: String,
    val body: String,
    val createdAt: Long,
    val updatedAt: Long,
)

/**
 * Lightweight metadata for list views: omits [Manuscript.body] to keep listings cheap.
 */
@Serializable
data class ManuscriptSummary(
    val id: ManuscriptId,
    val title: String,
    val updatedAt: Long,
)
