package dev.noveditor.core.model

import kotlinx.serialization.Serializable
import kotlin.jvm.JvmInline

/**
 * Stable identifier of a [Novel] (連載・単発を問わず1つの小説).
 *
 * Wraps a [String] so novel ids are not confused with [EpisodeId]s or arbitrary strings at the
 * type level. The concrete value is generated by an adapter (e.g. `crypto.randomUUID()` on web,
 * `UUID` on Android) and injected into [core][dev.noveditor.core]; `core` never mints ids itself.
 */
@Serializable
@JvmInline
value class NovelId(val value: String)

/**
 * Stable identifier of an [Episode] (小説内の1話).
 *
 * Wraps a [String] for the same type-safety reason as [NovelId]; values are adapter-minted.
 */
@Serializable
@JvmInline
value class EpisodeId(val value: String)

/**
 * A novel (小説): the container that binds an ordered list of [Episode]s. A single-shot work
 * (一話完結) is simply a novel with one episode, expressed in the same model.
 *
 * [episodeOrder] is the single source of truth for episode ordering — episodes themselves carry
 * no order field, so a reorder is one novel update and ordering cannot drift between records.
 *
 * Timestamps are epoch milliseconds supplied by an adapter (`core` holds no clock).
 * Serializable via kotlinx.serialization so adapters share one canonical persistence shape.
 */
@Serializable
data class Novel(
    val id: NovelId,
    val title: String,
    val synopsis: String = "",
    val episodeOrder: List<EpisodeId>,
    val createdAt: Long,
    val updatedAt: Long,
)

/**
 * A single episode (話) within a [Novel]: the unit of body text, generalizing the legacy
 * [Manuscript] by adding [novelId]. Title is the episode title (話タイトル).
 *
 * Ordering is owned by the parent [Novel.episodeOrder], not stored here.
 * Timestamps are epoch milliseconds supplied by an adapter (`core` holds no clock).
 */
@Serializable
data class Episode(
    val id: EpisodeId,
    val novelId: NovelId,
    val title: String,
    val body: String,
    val createdAt: Long,
    val updatedAt: Long,
)

/**
 * Lightweight metadata for the novel list view: omits bodies, exposing [episodeCount] for display.
 */
@Serializable
data class NovelSummary(
    val id: NovelId,
    val title: String,
    val episodeCount: Int,
    val updatedAt: Long,
)

/**
 * Lightweight metadata for the episode list view: omits [Episode.body] to keep listings cheap.
 */
@Serializable
data class EpisodeSummary(
    val id: EpisodeId,
    val title: String,
    val updatedAt: Long,
)
